all:
  children:
    resiliencia:
      hosts:
        vps1:
          ansible_host: 203.0.113.10 # IP publico de exemplo
          wg_ip: 10.0.0.10
          patroni_name: vps1
          patroni_priority: 100
          nextcloud_server_id: 1

        vps2:
          ansible_host: 203.0.113.11 # IP publico de exemplo
          wg_ip: 10.0.0.11
          patroni_name: vps2
          patroni_priority: 90
          nextcloud_server_id: 2

        vps3:
          ansible_host: 203.0.113.12 # IP publico de exemplo
          wg_ip: 10.0.0.12
          patroni_name: vps3
          patroni_priority: 80
          nextcloud_server_id: 3
    nextcloud_cluster:
      children:
        resiliencia: {}
      vars:
        ansible_user: ansible-lc
        ansible_python_interpreter: /usr/bin/python3
        ansible_port: 20012
        ansible_ssh_private_key_file: ~/.ssh/librecode/ansible/ansible-lc
